### ISSUE TITLE
Tracking Issue for April 2021 Housekeeping Sprint

### ISSUE THREAD

**Issue by BastiDood** [smtnhacker/OJHacker#5]
# Work-in-progress Refactors
In order to keep the codebase maintainable, it is necessary to clean up the current project structure. The following items below are the milestones we must meet before implementing new features for OJ Hacker. This issue will be edited as more progress is made and more milestones are included (if any).

- [x] #1 Move all source files to `src/` folder
- [ ] #2 Refactor test case generator queries
- [ ] Fully refactor test generators such that is more _Pythonic_
- [ ] #3 #4 Refactor command dispatch to make proper use of [discord.py's built-in command framework](https://discordpy.readthedocs.io/en/stable/ext/commands/index.html)
- [ ] Fully modularize the project so that [`src/main.py`](https://github.com/smtnhacker/OJHacker/blob/main/src/main.py) only contains glue code
- [ ] Unit test the modularized components of the project

**Comment by smtnhacker** [comment]
Refactored and modularized the test case generators for current problems. Please review the pull request if it is good enough @Some-Dood
